name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} <<EOF
          cd ~/tibia/server
          source /root/.bashrc
          source /usr/local/rvm/scripts/rvm
          source /root/.nvm/nvm.sh

          nvm install 16
          rvm use 3.2.2
          nvm use 16

          git pull

          yarn install
          yarn run build

          sudo systemctl restart tibia_server.service
        EOF
